name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
- monalisa
- nat
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com
  validations:
    required: false
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
    value: "A bug happened!"
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: Version
    description: What version of our software are you running?
    options:
    - 1.0.2 (Default)
    - 1.0.3 (Edge)
  validations:
    required: true
- type: dropdown
  id: browsers
  attributes:
    label: What browsers are you seeing the problem on?
    multiple: true
    options:
    - Firefox
    - Chrome
    - Safari
    - Microsoft Edge
- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
- type: checkboxes
  id: terms
  attributes:
    label: General Information
    description: This provides an overall summary or context of a member, when they became involved and how many days they have worked. This could be supplemented with a contribution vote by peers to capture the more intangible contribution a member has made.
    options:
    - label:  Date joined ACO - [Month/Day/Year]
      required: true
    - label: Days / Hours worked overall - [00 Days/Hours]
      required: true
    - label: Cost of contribution (from member perspective) - [$ 0]
      required: true
    - label: Contribution vote
      required: true
- type: checkboxes
  id: terms
  attributes:
    label: General Information
    description: This provides an overall summary or context of a member, when they became involved and how many days they have worked. This could be supplemented with a contribution vote by peers to capture the more intangible contribution a member has made.
    options:
    - label:  Date joined ACO - [Month/Day/Year]
      required: true
    - label: Days / Hours worked overall - [00 Days/Hours]
      required: true
    - label: Cost of contribution (from member perspective) - [$ 0]
      required: true
    - label: Contribution vote
      required: true
- type: checkboxes
  id: terms
  attributes:
    label: General Information
    description: This provides an overall summary or context of a member, when they became involved and how many days they have worked. This could be supplemented with a contribution vote by peers to capture the more intangible contribution a member has made.
    options:
    - label:  Date joined ACO - [Month/Day/Year]
      required: true
    - label: Days / Hours worked overall - [00 Days/Hours]
      required: true
    - label: Cost of contribution (from member perspective) - [$ 0]
      required: true
    - label: Contribution vote
      required: true
- type: checkboxes
  id: terms1
  attributes:
    label: fe ftr
    description:  member, when they became involved and how many days they have worked. This could be supplemented with a contribution vote by peers to capture the more intangible contribution a member has made.
    options:
    - label: First label
      required: true
    - label: 2 label
      required: true
    - label: 3 label
      required: true
    - label: 4 label
      required: true
