on:
  # https://crontab.guru/
  schedule:	
  - cron: 0 0 * * 0
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
name: Generate report

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: imjohnbo/workflow-reports-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        owner: SecretDecks-org
