name: Weekly Report
on:
  schedule:
    - cron: '*/5 * * * *' # At 06:00 on Sunday
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/activity-report@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
